# Introduction {#intro}

`r if(identical(gitbook_on, FALSE))knitr::asis_output("This report is available as both a pdf and as an online interactive report at https://newgraphenvironment.github.io/fish_passage_bulkley_2022_reporting/. We recommend viewing online as the web-hosted version contains more features and is more easily navigable. Please reference the website for the latest version number and download the latest pdf from https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/raw/master/docs/bulkley2022.pdf")` 


`r if(identical(gitbook_on, FALSE)){knitr::asis_output("<br>")}`

This report is part of a larger effort by the Society for Ecosystem Restoration Northern British Columbia (SERNbc) in the Skeena River watershed which began in 2020.  Although this document discusses crossings in the the Bulkey River watershed group only (as defined by the Freshwater Atlas of BC), project activities since 2020 have also included sites in the Morice River watershed group with expansion of the study area in 2022 to include the Zymoetz Watershed Group and the Kispiox River watershed group.  At the time of reporting, additional reporting related to 2022 fieldwork planning and results interpretation for these other watershed groups was underway and available [here](https://newgraphenvironment.github.io/fish_passage_skeena_2022_reporting/).  Work in 2022 builds on planning which began in 2018 by @irvine2018AnalysisPriority, documentation in @mazany-wright_etal2021BulkleyRiver and reporting from field activities conducted in 2020 [@irvine2021BulkleyRiver] and 2021 [@irvine2022BulkleyRiver].  Past years of SERNbc reporting can be viewed interactively [here](https://newgraphenvironment.github.io/fish_passage_bulkley_2020_reporting/) and [here](https://newgraphenvironment.github.io/fish_passage_skeena_2021_reporting/).

<br>

Please note that at the time of reporting, this document was in draft format and changing over time.  Version numbers are logged for each release with modifications, enhancements and other changes tracked [here](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/blob/master/NEWS.md) with issues tracked [here](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2022_reporting/issues). 

<br>


The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage]. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

Although remediation and replacement of stream crossing structures can have benefits to local fish populations, the costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify. Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of ways are not always considered ethical under all circumstances from all perspectives. When funds are finite and invested groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored collaboratively alongside the cost benefits and ethics of alternative investment activities including transportation corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian/floodplain restoration, habitat complexing, water conservation,  commercial/recreational fishing management, salt water interventions and research.
